### ISSUE TITLE
Neposílat změnu výstupu, který již má požadovaný stav

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/rcs-lib-XpressNET-qt#16]
* Trojstavová logika výstupů netřeba, na začátku vše nastavit na 0.
* Implementovat v API, pro návěstidla neplatí.

**Comment by petrilakm** [comment]
Jak poznáš že má výstup požadovaný stav? Z ručního ovladače to klidně nekdo může nečekaně změnit.

**Comment by malinajan** [comment]
Ze svého vnitřního stavy výstupů. Může, ale tohle je spíš otázka na to, jaké jsou výstupy z hJOP.

Typy výstupů:
 * Výhybka: když někdo změní polohu, hJOP to pozná zpětnou vazbou, takže vždy aktivuje správný výstup.
 * osvětlení: hJOP stejně posílá jen, když uživatel udělá změnu a nepozná, že někdo z ovladače osvětlení vypnul. Tedy když ho někdo vypne, klikne na reliéfu "vypnout" a pak "zapnout". Minimálně jedna z těch voleb musí poslat příkaz centrále.
 * Návěstidla "S-COM": pro ty neplatí.
 * Návěstidla "1/0": tady se už teď posílají jen změny přímo z hJOP.
 * Přejezd: když tady někdo ručně aktivuje nějaký výstup, hJOP to pozná, může to hJOP mírně zmást. Ale to nemá nic společného s tím, jestli se posílají změny.
 * Rozpojovač: první zákmit bude chybět. hJOP stejně na začátku neresetuje ani teď.
 * ... nějaké další výstupy?

**Comment by malinajan** [comment]
Myslím, že aktuálně jediný typ bloku, který si explicitně nuluje stav před změnou, je výhybka: když zavolám změnu polohy, nastaví oba výstupy (jeden aktivuje, druhý deaktivuje). Připadá mi, že nastavení deaktivace je zbytečné, cílem této feature je právě to, aby se deaktivace neposílala.

Všechny ostatní bloky očekávají, že výstup v takovém stavu, v jakém ho naposled zanechala hJOP, případně mají nějakou zpětnou vazbu, ze které stav poznají.
